<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_diachib2</name>
   <tag></tag>
   <elementGuidId>4d5fe50a-924f-4592-b852-d9bfb5049cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/form/div[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>171b8b55-e4da-40fa-b4aa-3d9c5293a041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd0780be-d24b-4bfb-8444-bae90c17e682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-2-20 form-control rounded-left </value>
      <webElementGuid>fef5a729-ef60-46d1-90fa-507cd06accdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-edit-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/div[@class=&quot;modal-body px-4 px-md-3&quot;]/div[@class=&quot;px-md-5 py-md-3&quot;]/form[1]/div[@class=&quot;form-group required&quot;]/input[@class=&quot;input-0-2-20 form-control rounded-left&quot;]</value>
      <webElementGuid>ab395f5b-3978-4fa2-a26d-99ffce9e3e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>67872441-321c-4525-a753-394e8b85da27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-edit-modal']/div/div/div/div[2]/div/form/div[5]/input</value>
      <webElementGuid>b6788271-8b98-4581-9910-e2a20214bae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>909e21c5-260e-4b4c-b40a-01be9810ebeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
