<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng k</name>
   <tag></tag>
   <elementGuidId>cb0086f4-dd5d-4fca-bbc5-73f6580f46e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='top-navigation']/div/ul/li[5]/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-primary.mx-2.signup-button.px-5.py-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d1213c2-7e71-4892-9c75-4859276b123c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary mx-2 signup-button px-5 py-2</value>
      <webElementGuid>4b2d45bb-7ce5-4b99-886d-b552cdb2589d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b33f6768-ffbe-4f02-8866-79083883954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/nguoi-tim-viec/dang-ky</value>
      <webElementGuid>992c94f4-ce63-40a0-89d7-d09d70ecabe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>f38cb6a1-a8bf-413d-8c24-670969304d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-navigation&quot;)/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;navbar-nav ml-auto d-none d-lg-flex&quot;]/li[@class=&quot;nav-item dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right profile-menu shadow-sm p-0 show&quot;]/div[@class=&quot;content row no-gutters px-3 py-3&quot;]/div[@class=&quot;d-flex col-12 justify-content-center mb-2 font-weight-bold&quot;]/a[@class=&quot;btn btn-outline-primary mx-2 signup-button px-5 py-2&quot;]</value>
      <webElementGuid>1e95e674-68d3-422a-933e-5e5c306fc47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f579656-2fab-4fad-a140-fbd89c888c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary mx-2 signup-button px-5 py-2</value>
      <webElementGuid>bf8dc427-5064-456e-bb0a-bf41ec3a324b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bca402a4-42a4-4040-aa07-6593fc50c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/nguoi-tim-viec/dang-ky</value>
      <webElementGuid>4b825b9f-ff69-4ab2-87cd-adea5d1dfee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>1636870c-ac4a-4218-9fdf-918c583ccbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-navigation&quot;)/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;navbar-nav ml-auto d-none d-lg-flex&quot;]/li[@class=&quot;nav-item dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right profile-menu shadow-sm p-0 show&quot;]/div[@class=&quot;content row no-gutters px-3 py-3&quot;]/div[@class=&quot;d-flex col-12 justify-content-center mb-2 font-weight-bold&quot;]/a[@class=&quot;btn btn-outline-primary mx-2 signup-button px-5 py-2&quot;]</value>
      <webElementGuid>84d63412-bfa3-4d2a-856d-e775c1fc5f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc65862c-ee9f-446b-ba72-31d8ebf6acf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary mx-2 signup-button px-5 py-2</value>
      <webElementGuid>c4bd2584-3cc2-4e84-aa01-9a2c7a2acbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4a793a4-f614-4503-ab0e-770041b57dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/nguoi-tim-viec/dang-ky</value>
      <webElementGuid>1343db21-9202-4530-b6de-dc1da8048229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>bfa64def-6e93-439e-ad21-345d5be767a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-navigation&quot;)/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;navbar-nav ml-auto d-none d-lg-flex&quot;]/li[@class=&quot;nav-item dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right profile-menu shadow-sm p-0 show&quot;]/div[@class=&quot;content row no-gutters px-3 py-3&quot;]/div[@class=&quot;d-flex col-12 justify-content-center mb-2 font-weight-bold&quot;]/a[@class=&quot;btn btn-outline-primary mx-2 signup-button px-5 py-2&quot;]</value>
      <webElementGuid>6480d65f-a1da-4353-bb9a-2efc9e1d5aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='top-navigation']/div/ul/li[5]/div/div/div/a[2]</value>
      <webElementGuid>8adb3be0-a8c5-4172-8e75-d61c82d45bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng ký')]</value>
      <webElementGuid>612b4a81-3962-460d-9a81-c61d10871010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/following::a[1]</value>
      <webElementGuid>ad42a5c7-835e-40de-bb2b-39084f79d5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/following::a[2]</value>
      <webElementGuid>bcc25a75-49a4-48a1-b30a-a4869b8f56b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hồ sơ xin việc'])[1]/preceding::a[2]</value>
      <webElementGuid>d6f47e33-4724-4b4b-bab1-c92c8854675b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc đã lưu'])[1]/preceding::a[3]</value>
      <webElementGuid>cecc7daa-8e1b-4740-86a5-ee0d1a9e1c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/nguoi-tim-viec/dang-ky')]</value>
      <webElementGuid>2fd89fcc-00ed-40df-9295-4682010caa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/a[2]</value>
      <webElementGuid>3a9c110a-8294-43a9-aa4b-9eabcd284d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/nguoi-tim-viec/dang-ky' and (text() = 'Đăng ký' or . = 'Đăng ký')]</value>
      <webElementGuid>31fb9617-5fb3-4810-9813-afce122bd34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
