<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lu h s</name>
   <tag></tag>
   <elementGuidId>f203c23a-d233-47e8-bcb5-e30023490975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go-to-next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#go-to-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>194f1adb-cf9b-4529-a52b-d53ff58afea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5ab748a5-1ed5-4ba6-b207-07033f00cca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-next</value>
      <webElementGuid>d372febb-72ba-4dad-a490-d59202f09cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary d-flex align-items-center font-weight-bold px-3 py-2</value>
      <webElementGuid>ee13a821-d5b3-432d-b04d-7bddaf2c2c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu hồ sơ</value>
      <webElementGuid>faf7db3b-9780-4588-b05a-c6c3cfc45a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-to-next&quot;)</value>
      <webElementGuid>0e15b5cd-cd70-458e-9327-d311a5e5936e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>acce2986-8003-420a-9edd-7ede1fa132ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e28f128-3712-438e-9452-121c8016f5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-next</value>
      <webElementGuid>11d3c858-8870-4a0d-8d0b-f3d69474b1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary d-flex align-items-center font-weight-bold px-3 py-2</value>
      <webElementGuid>f1d9e6e8-c98b-4c21-a421-543302b7d9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu hồ sơ</value>
      <webElementGuid>37c0de12-d3db-4ebb-814a-187c7fe2629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-to-next&quot;)</value>
      <webElementGuid>7522c578-26cd-4af0-8b0b-a649f77ea875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cffee53-7e05-42d3-94e2-4ade6fe2b658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>74be3b92-9b8d-41a6-b4df-864b300a0a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-next</value>
      <webElementGuid>8a6a1107-c412-4168-9604-4b40a52e9763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary d-flex align-items-center font-weight-bold px-3 py-2</value>
      <webElementGuid>d98de54e-e6e3-4958-96b0-68e83d8b3587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu hồ sơ</value>
      <webElementGuid>62fdfb32-bb7f-4a6a-b685-749fb88bbe3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-to-next&quot;)</value>
      <webElementGuid>a0d54f1a-065c-43a7-9075-549cd09e643d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go-to-next']</value>
      <webElementGuid>b45b4c8c-5327-4a22-9fb1-5da3951a6b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/div/form/div[4]/div/div/button</value>
      <webElementGuid>98c85a5f-e8c0-4adb-a9a0-a7c04960740a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/following::button[1]</value>
      <webElementGuid>6e502635-e666-4a80-bfc9-3a4abbd03d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Không cho phép tìm kiếm'])[1]/following::button[1]</value>
      <webElementGuid>24b12ec1-f1c4-4373-bbfb-ee6efdb4a6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về CareerLink'])[1]/preceding::button[1]</value>
      <webElementGuid>c2ff8c6a-d992-40b5-9376-42c645971426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về chúng tôi'])[1]/preceding::button[1]</value>
      <webElementGuid>1fad70ad-a526-47de-9611-65c45b80fb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lưu hồ sơ']/parent::*</value>
      <webElementGuid>c8370bbb-e2f1-4d81-8531-63d6ddad321b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>5c6b163b-5428-4d1c-b410-72f22eac2a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'go-to-next' and (text() = 'Lưu hồ sơ' or . = 'Lưu hồ sơ')]</value>
      <webElementGuid>14340eed-d7bc-4f84-b2b9-ffed22117a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
