<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trang thai HS</name>
   <tag></tag>
   <elementGuidId>c3a50376-aca4-4198-8c65-a8fcab28ce7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/div/form/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>071a7584-7e6e-463e-80a8-abf98cc3441f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>30ffa4de-eb55-46b1-808e-a50d7cbc1568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/div[@class=&quot;container-0-2-51&quot;]/form[@class=&quot;search-config&quot;]/div[@class=&quot;search-config-option&quot;]/label[@class=&quot;fluent-radio&quot;]/div[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>d3739fd0-c671-4f16-b290-1c4f8d08ab4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a48894e-a218-47c4-81fc-6b8572c8a7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>45d92b9a-44e8-40c7-a8ca-1918cea78fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/div[@class=&quot;container-0-2-51&quot;]/form[@class=&quot;search-config&quot;]/div[@class=&quot;search-config-option&quot;]/label[@class=&quot;fluent-radio&quot;]/div[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>63a1a2a4-4de4-4b83-8290-1eb4a2e6821a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/div/form/div/label/div</value>
      <webElementGuid>2ac4903b-5af5-442b-b1b8-244b11937b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>f44b67d0-0aec-45b4-b3ed-5f79d93484b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
