<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trng thi h s_checkmark</name>
   <tag></tag>
   <elementGuidId>d5e89bb3-7b27-4f6c-aa3a-38f5515e42f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/div/form/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c2c1fb0-7a99-4851-8e6a-dd5be8e59eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>6a52d150-38c9-467c-b6a1-c633243fef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/div[@class=&quot;container-0-2-51&quot;]/form[@class=&quot;search-config&quot;]/div[@class=&quot;search-config-option&quot;]/label[@class=&quot;fluent-radio&quot;]/div[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>66c297af-7aff-46c8-84ba-37ab55126aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5296ad46-ae9a-4ce4-95e4-55055bde42ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>0a83fa13-2592-4e49-8b21-9f48e7281101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/div[@class=&quot;container-0-2-51&quot;]/form[@class=&quot;search-config&quot;]/div[@class=&quot;search-config-option&quot;]/label[@class=&quot;fluent-radio&quot;]/div[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>74584836-3c74-479e-9ae1-7350eb5cfd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/div/form/div/label/div</value>
      <webElementGuid>6b81c1a1-0148-4b2a-8566-88fbdfdbee9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>2fcc042b-905a-4a5c-9cae-8bcfb0f88fbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
