<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tt c qunhuyn</name>
   <tag></tag>
   <elementGuidId>9a4d0aab-7819-4e76-b79d-33c9ada48e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[7]/div/div/div/div[2]/div/button/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>205eb6db-ce18-48f7-bbd2-b1eef21ac4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tất cả quận/huyện</value>
      <webElementGuid>bf252c50-dc83-4370-87cf-50f7acc28a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;mb-2 position-relative&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;ml-2&quot;]/div[@class=&quot;dropdown cl-select&quot;]/button[@class=&quot;btn button-dropdown&quot;]/div[1]/div[1]</value>
      <webElementGuid>cce2ef5a-e407-4dc4-9dda-8cdb7b538a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3aea87d3-c008-455b-9f0e-8cde1ecbb819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tất cả quận/huyện</value>
      <webElementGuid>3b1802a3-a375-44db-b2d4-3dd0284b3b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;mb-2 position-relative&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;ml-2&quot;]/div[@class=&quot;dropdown cl-select&quot;]/button[@class=&quot;btn button-dropdown&quot;]/div[1]/div[1]</value>
      <webElementGuid>83e01bda-44db-4c0c-b6e2-3630fbf840e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[7]/div/div/div/div[2]/div/button/div/div</value>
      <webElementGuid>155d4699-8c8b-4aaf-971d-ace93291bb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hà Nội'])[1]/following::div[5]</value>
      <webElementGuid>d015accd-9b47-4898-932a-9ad83f262f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nơi làm việc ưa thích'])[1]/following::div[12]</value>
      <webElementGuid>a603cb9b-8c18-4695-acf0-73045bc997f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm nơi làm việc'])[1]/preceding::div[2]</value>
      <webElementGuid>ce0b7b6a-aab8-4b33-8cd0-7d78c6eac5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mục tiêu nghề nghiệp'])[3]/preceding::div[3]</value>
      <webElementGuid>02af4dad-48db-458d-aa43-f6f3f76fbfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tất cả quận/huyện']/parent::*</value>
      <webElementGuid>1d7b205a-d32e-4532-b578-ade1227f1d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/div/div</value>
      <webElementGuid>0bcbcbaf-5e7f-4c4c-9d3c-2e98610c0754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tất cả quận/huyện' or . = 'Tất cả quận/huyện')]</value>
      <webElementGuid>d8ec6087-8653-430b-9902-ca9dfe454922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
