<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ng k_cli-angle-down ml-xl-3 mr-1</name>
   <tag></tag>
   <elementGuidId>d418e836-bb5c-40b0-b21b-c835cabb6a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.cli-angle-down.ml-xl-3.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profileMenu']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>06d97fc6-cf1f-42bc-be89-dcbcc8be9f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>6edb3cd6-0fa3-48fc-9ea9-33181a2b93cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>cbfc829e-5f33-43fb-a506-31efdc55b1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f8cce2de-ccc2-432c-90e0-059971ad7121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>2a68b55e-e731-4368-9420-49bdd55a3d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>636a3739-0438-449a-a065-e2fe30b9e4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4f6cfa5-0c1b-4d70-9699-1f0bd02f6cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>d437b70d-5db7-48a0-b134-589079c1fdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>4c293268-3def-41c5-92ca-a09924fb0360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2c8dfde6-cd3f-4d88-9314-36724a459c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>75452396-6a11-4e3c-af90-4b4002db8f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>4229d1c6-c5d5-4ed4-93ee-e057510fa5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>14cadad0-c148-448f-a5b7-9c18500e27f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>54cd8263-20bb-4115-b91c-3bcc671297bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>2c842932-2617-4c99-8139-c1605049efd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f2d7535e-8ffa-41ac-baaf-8687b5822484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>5a0c81ea-775f-4cb8-820b-3ce33684d503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>f1494ff0-9c66-4d3f-b0bb-bc6b4311a167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>254af37e-5f4c-4234-bbcb-f282ff236c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>c84aa31f-2f3a-4ab9-919f-06ac939d6747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>42a2881b-c385-4645-ba22-73f5d060494f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4e44cbba-48cb-4360-8e8d-8688dec5a338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>38dab4cc-fec8-48f0-8b1d-f4fbeb10ae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>f13d871d-925f-4f44-8646-784260269bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>936dfa33-f201-43a5-be43-520115761756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>0034a5dc-ed7d-4cb4-9dcc-47c3503a10d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>3a9ad96c-0f93-4b29-9bb2-b8d42dd925a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1ed35d39-9e0b-4ce1-bace-ab412715e25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>d591663d-d3b7-4c4a-8bcf-a89f5732b545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>cb7818a8-a597-498a-8012-44eb83d78601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>90325245-55ff-4544-bfbc-f0ce1ccf29ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>ace8a5e2-4ab9-474d-a6ea-752531da2376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>d5d2ee73-9be3-492e-b7d9-f455f817c3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>45a1cc74-0202-48cc-9bf5-4b48b83274c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>271f63b6-9ed5-4c19-a88c-bb78b41b6580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>3b3807c1-0f4a-4045-b2fd-bca75891c4df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='profileMenu']/i</value>
      <webElementGuid>7167d18b-2c7a-4ff0-a58a-349404fe8f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>48881dee-5612-4df4-8bae-fecf3bd5b184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
