<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Nguyn Hong Anh_cli-angle-down ml-3 mr-1</name>
   <tag></tag>
   <elementGuidId>199b5f29-d60f-49e3-96dd-14a7d76010d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profileMenu']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.cli-angle-down.ml-3.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4313c74a-b430-406c-ae0a-34ff0693066a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-3 mr-1</value>
      <webElementGuid>0c9b4e28-4704-4fd0-9829-edad8f1218fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-3 mr-1&quot;]</value>
      <webElementGuid>65b95ef3-7d6b-40de-b6a9-d16e1b3af236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='profileMenu']/i</value>
      <webElementGuid>fc15c81f-e11c-4d99-a6f9-210b75177f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>75928c2a-ac75-4cf9-b39b-55f255ddd3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
