<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vic lm cho ng vin chuyn nghip_91f24d8_3caeb4</name>
   <tag></tag>
   <elementGuidId>d56d2ea8-0812-4749-9e97-c300f386c424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='91f24d89-5262-4b99-9c5b-d01cca6d81c7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#91f24d89-5262-4b99-9c5b-d01cca6d81c7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f894b31-eac5-48f1-bf66-ec4467b251ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>527ac8f6-e882-4859-8446-fd19e565ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>91f24d89-5262-4b99-9c5b-d01cca6d81c7</value>
      <webElementGuid>f5c582b5-dddf-47b5-81ef-c46dc3a5afa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f7f9a06-3f5d-4269-a052-a37e6581df91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6aac2d59-7872-4947-9a37-4e34d8aff8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d72af638-f8f0-45c5-9c02-34e4fe620283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>fbb066d1-232d-4af0-9dcc-097d13d57306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a493607-7031-4a26-abbd-981df3389c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;91f24d89-5262-4b99-9c5b-d01cca6d81c7&quot;)</value>
      <webElementGuid>4a36fe7e-66f2-4b7c-a3de-b554fa9553c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='91f24d89-5262-4b99-9c5b-d01cca6d81c7']</value>
      <webElementGuid>bbbc2f3a-c1b5-4ced-b8bc-9a7c825ff3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>14042101-cd44-47ef-8610-34a7fe2653d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '91f24d89-5262-4b99-9c5b-d01cca6d81c7' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>060ac435-1e16-478e-bbba-0839eaa8574c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
