<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-0-2-11 form-control rounded-le_2a66a4</name>
   <tag></tag>
   <elementGuidId>3da08e9f-9df8-482d-aebc-aa3c9ce8f315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-0-2-11.form-control.rounded-left.is-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26b733c9-b9a8-43d4-9f0f-d129ff0ae578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8db555f-b421-41a5-b50d-8967569ec2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-2-11 form-control rounded-left is-invalid</value>
      <webElementGuid>e237b0e5-88cd-4c7c-88f5-3afc85e3acf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[@class=&quot;personalDetailsFormInput-0-2-7&quot;]/label[@class=&quot;w-100&quot;]/input[@class=&quot;input-0-2-11 form-control rounded-left is-invalid&quot;]</value>
      <webElementGuid>d493adaf-f401-490f-8fd7-a2682374080d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>435a0c75-3f80-4d51-ace5-83454611d551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/label/input</value>
      <webElementGuid>ddc87bd2-848c-4b13-b100-ba99f181787d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>90577ca4-4276-4354-8639-5feaf4ced895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
