<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nhn vin ton thi gianNhn vin ton thi _5243c0</name>
   <tag></tag>
   <elementGuidId>009694e9-07f0-465a-a248-1bc8332d5c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[4]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>70b1576b-6052-4954-b321-c447e7603d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6a09951-66bb-46d7-8f13-22b6e8b8ae88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fluent-form-control </value>
      <webElementGuid>79d5aee0-97db-4d60-b02c-eb29f544926d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác</value>
      <webElementGuid>0b3e6c57-58a4-4a3f-93e4-ca2bf47c716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fluent-select&quot;]/select[@class=&quot;form-control fluent-form-control&quot;]</value>
      <webElementGuid>fdd56b4c-d16d-4f44-a849-43b3a51720bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>feb8fd03-08c6-442f-8763-65c263212665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d5ef6c5-84ca-4a3f-af6a-0e69263e6cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fluent-form-control </value>
      <webElementGuid>bfbed227-27dd-4414-814b-e91eedc8df39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác</value>
      <webElementGuid>aaaad100-2170-434d-800b-8a545b2cb5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fluent-select&quot;]/select[@class=&quot;form-control fluent-form-control&quot;]</value>
      <webElementGuid>35b466d6-ecc1-408a-aa1a-0adcc12eeaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>64206ed8-78f4-488a-ae6f-a26aadfa97e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f2c471e3-f077-4625-bde0-05dd4d0db01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fluent-form-control </value>
      <webElementGuid>6cc87313-8d61-4945-9c85-1c3346ccc307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác</value>
      <webElementGuid>1d324fa5-0767-48a2-9218-5d0ecdafebdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fluent-select&quot;]/select[@class=&quot;form-control fluent-form-control&quot;]</value>
      <webElementGuid>bbfd9c6f-0901-4724-b334-604ae2f3abbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[4]/div/div/select</value>
      <webElementGuid>002f6691-012b-4367-80c6-02e355586958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại công việc'])[1]/following::select[1]</value>
      <webElementGuid>3353069a-138e-4879-808c-081d54366897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mức lương mong muốn'])[1]/following::select[2]</value>
      <webElementGuid>2522eb78-18d6-4ebe-b09a-cafaaeb147da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cấp bậc mong muốn'])[1]/preceding::select[1]</value>
      <webElementGuid>7a284011-ed75-406a-b1f1-14e3a7d1b22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngành nghề mong muốn'])[1]/preceding::select[2]</value>
      <webElementGuid>d9615cbc-001e-44c5-b772-faca6db307fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>97bf2017-0f9c-4977-b60d-eec0a75c7c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác' or . = '...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác')]</value>
      <webElementGuid>8fce9564-423a-4a0a-b700-2f1d4aab7430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
