<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_S cpTrung cpCao cpThnh thoBn ng</name>
   <tag></tag>
   <elementGuidId>b032cf50-7669-4077-be3c-71f5795a28e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div/div/div[2]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b6bdeaef-21cd-4c97-a18a-1e410a2b4186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e955173a-38e4-451b-9478-1730fca986af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fluent-form-control </value>
      <webElementGuid>2449ee1d-95cd-4fe1-9b50-598dfe254e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...Sơ cấpTrung cấpCao cấpThành thạoBản ngữ</value>
      <webElementGuid>a558d444-e951-4dfc-b726-944687d97811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;root-0-2-35&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-6&quot;]/div[@class=&quot;flex-fill&quot;]/div[@class=&quot;fluent-select&quot;]/select[@class=&quot;form-control fluent-form-control&quot;]</value>
      <webElementGuid>c77dc963-0daf-4b99-aea5-8cb5f31e2619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div/div/div[2]/div/div/select</value>
      <webElementGuid>1414a228-ccfd-45c4-a136-50022c4f9e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trình độ'])[1]/following::select[1]</value>
      <webElementGuid>ee8bda21-e811-4275-875e-92f4655a0f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếng Anh'])[1]/following::select[1]</value>
      <webElementGuid>cf064ed6-ad04-4a83-b333-a2fe48346e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm ngôn ngữ'])[1]/preceding::select[1]</value>
      <webElementGuid>f3d617c1-2b9f-4fb3-a411-8002461392e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưu và Thoát'])[1]/preceding::select[1]</value>
      <webElementGuid>8d457657-f734-4a52-82ed-077b085802e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>194227b1-e4ad-4ab3-adb8-4a774d30cb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '...Sơ cấpTrung cấpCao cấpThành thạoBản ngữ' or . = '...Sơ cấpTrung cấpCao cấpThành thạoBản ngữ')]</value>
      <webElementGuid>e47e5e52-e5cb-430f-b69c-f0e4a328fcf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
