<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_H S phm K Thut Hng Yn</name>
   <tag></tag>
   <elementGuidId>91e41239-003d-4d5d-a712-13d9e43203c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[2]/div/div/div/div/div[4]/div/button[36]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1664a917-9a27-42cd-9b18-15e093a3391f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item cl-select--item</value>
      <webElementGuid>7bd441da-0e23-4367-beae-1ffa297d439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b23602a2-c9b2-45b1-96ac-d4c27815eddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ĐH Sư phạm Kỹ Thuật Hưng Yên</value>
      <webElementGuid>fb0baa88-0d34-4040-8258-931a09a4ceb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;dropdown cl-select show&quot;]/div[@class=&quot;dropdown-menu shadow-sm menu-0-2-18 cl-select--menu cl-scrollbar pt-0 show&quot;]/div[4]/div[@class=&quot;ml-2&quot;]/button[@class=&quot;dropdown-item cl-select--item&quot;]</value>
      <webElementGuid>61f82e50-36d0-43d5-aad5-ae980f039db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[156]</value>
      <webElementGuid>1a986c6f-3fad-40a5-b9c5-fd20ae84d079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[2]/div/div/div/div/div[4]/div/button[36]</value>
      <webElementGuid>5a6924a0-a09c-4551-887c-ff9cd7397988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐH Sư phạm Kỹ Thuật Nam Định'])[1]/following::button[1]</value>
      <webElementGuid>f1f83892-3166-43fa-8bf3-cfddfc4a95a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐH Sư phạm Nghệ thuật Trung ương'])[1]/following::button[2]</value>
      <webElementGuid>0abcc9ac-1a6d-4ab0-928e-87a3ed2b7317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐH Sư phạm Hà Nội 2'])[1]/preceding::button[1]</value>
      <webElementGuid>a201e532-cd8d-42c9-8ef4-d1d3568c7f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐH Sư phạm Hà Nội'])[1]/preceding::button[2]</value>
      <webElementGuid>3a807476-1638-4b8e-a67d-fa85332a7ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ĐH Sư phạm Kỹ Thuật Hưng Yên']/parent::*</value>
      <webElementGuid>e094f7bc-c6db-4720-96ee-f2073f726649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button[36]</value>
      <webElementGuid>8ac205eb-008c-4309-8053-92fe712b2354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ĐH Sư phạm Kỹ Thuật Hưng Yên' or . = 'ĐH Sư phạm Kỹ Thuật Hưng Yên')]</value>
      <webElementGuid>0e89c941-7577-40fc-8756-6802584410cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
