<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lu h s</name>
   <tag></tag>
   <elementGuidId>caf93217-308d-4136-bbfe-0125b0f4222e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#go-to-next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go-to-next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>480b4ee7-ceef-4c58-abed-3f02fbaf600a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>971a71aa-9cef-481b-911b-7598f02f7e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-next</value>
      <webElementGuid>6febe269-2026-42d1-a0de-502d53a91f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary d-flex align-items-center font-weight-bold px-3 py-2</value>
      <webElementGuid>d58fef10-c648-4f54-80c5-f93824d9faa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu hồ sơ</value>
      <webElementGuid>f4fecb3a-7ad1-4409-a87a-afaa47c568a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-to-next&quot;)</value>
      <webElementGuid>95ee79db-655b-461d-9aa7-211489aed2d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go-to-next']</value>
      <webElementGuid>be0b81c5-8d05-424e-9a5f-71b422811382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/div/form/div[4]/div/div/button</value>
      <webElementGuid>3e240954-45d7-4be5-9625-0020d7e4f5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/following::button[1]</value>
      <webElementGuid>9019132f-dfef-442c-b709-282ede0fbb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Không cho phép tìm kiếm'])[1]/following::button[1]</value>
      <webElementGuid>98485ab9-0bd3-442b-b242-ec0469b3f961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về CareerLink'])[1]/preceding::button[1]</value>
      <webElementGuid>0d35a357-152a-411c-adc8-e257f6c49089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về chúng tôi'])[1]/preceding::button[1]</value>
      <webElementGuid>041303d1-b474-45a4-8a0a-c53245c57e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lưu hồ sơ']/parent::*</value>
      <webElementGuid>9ccb91c3-89ba-4e29-b574-5dbaddd14363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>7f1d2ddf-aba8-428b-a3a7-5fd71b176643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'go-to-next' and (text() = 'Lưu hồ sơ' or . = 'Lưu hồ sơ')]</value>
      <webElementGuid>94e222e0-8938-41cb-a3f8-c7fbe051ab55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
