<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ng k_cli-angle-down ml-xl-3 mr-1</name>
   <tag></tag>
   <elementGuidId>0aca6170-d8f8-4804-a38b-689567e1a6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.cli-angle-down.ml-xl-3.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profileMenu']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>439abeb9-efd8-4e1f-9632-7348d4cefa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cli-angle-down ml-xl-3 mr-1</value>
      <webElementGuid>535565a8-88c6-4edb-8a85-2df79784e42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileMenu&quot;)/i[@class=&quot;cli-angle-down ml-xl-3 mr-1&quot;]</value>
      <webElementGuid>24c65741-f85b-4eba-8e18-21a90e3daea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='profileMenu']/i</value>
      <webElementGuid>fd5d1966-98be-4ade-a868-41914a9bf87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>a519c79b-8716-4279-a120-696c801f52c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
