<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nhn vin ton thi gianNhn vin ton thi _5243c0</name>
   <tag></tag>
   <elementGuidId>e28bcef8-1a71-452a-8b2a-06d14527a938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/form/div[4]/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb7854af-c797-4714-88be-a743d4f442ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dff84d3b-8b3b-465d-8ec3-4bd9d7d8488d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fluent-form-control </value>
      <webElementGuid>6ac43600-c7b0-48b2-b4e0-28e3d9496283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác</value>
      <webElementGuid>0d74bc37-e2c9-4986-9ff7-1c5a2ed81733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fluent-select&quot;]/select[@class=&quot;form-control fluent-form-control&quot;]</value>
      <webElementGuid>955986a9-db1a-4689-b217-9e28ae7fe65e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[4]/div/div/select</value>
      <webElementGuid>fc8558f1-7b7a-4d2f-9a28-29a47d499daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại công việc'])[1]/following::select[1]</value>
      <webElementGuid>07eb73b9-4de7-4f2e-870f-aeec125f2954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mức lương mong muốn'])[1]/following::select[2]</value>
      <webElementGuid>38153db5-a6d7-4edc-9a77-eaeea871d580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cấp bậc mong muốn'])[1]/preceding::select[1]</value>
      <webElementGuid>73b9c5dc-ce50-4dca-a468-85557c3b900a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngành nghề mong muốn'])[1]/preceding::select[2]</value>
      <webElementGuid>3f6171ce-2e95-4265-b6d0-604f8e2cf11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>636fbacc-523d-4cba-843c-02560546bb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác' or . = '...Nhân viên toàn thời gianNhân viên toàn thời gian tạm thờiNhân viên bán thời gianNhân viên bán thời gian tạm thờiNhân viên hợp đồngKhác')]</value>
      <webElementGuid>4aa8ec9d-2eb7-4a0f-8190-9b061c4b5544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
