<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_z</name>
   <tag></tag>
   <elementGuidId>a0c234ca-dc8b-4771-948e-ab292e61cd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[5]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>97de361b-77ad-40b5-ae66-41aaa1a3340b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d3493bb-0961-457c-8e74-5dfdb9bb46bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>cb1cd9c9-2240-4605-a847-1381aed6c34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(Tuỳ chọn) Mô tả quá trình học vấn</value>
      <webElementGuid>1e4556df-30a3-4587-97d5-097eccf641ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-2-11 form-control rounded-left </value>
      <webElementGuid>80535800-be97-4c4a-a51d-43df6b8ec14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>z</value>
      <webElementGuid>f5699331-9849-4c34-b213-5edf1a7ef476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group&quot;]/textarea[@class=&quot;input-0-2-11 form-control rounded-left&quot;]</value>
      <webElementGuid>787c40a4-9cc7-4cc3-9fd7-41eba854ef18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[5]/textarea</value>
      <webElementGuid>c8b3cf94-1a7f-40c9-ace3-241a7fcbf9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quá trình học vấn'])[1]/following::textarea[1]</value>
      <webElementGuid>e01765f3-70dd-4ac8-931a-cb266ef702f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày Kết Thúc'])[1]/following::textarea[1]</value>
      <webElementGuid>d848371e-e217-4e49-b937-81e2709e45b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưu và Thoát'])[1]/preceding::textarea[1]</value>
      <webElementGuid>bc31677b-64b6-440c-a1a9-7d214e575ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/preceding::textarea[1]</value>
      <webElementGuid>58d29c36-2109-4e61-bf7b-290c065e327a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='z']/parent::*</value>
      <webElementGuid>a3d0831c-dae7-4ed3-ba3b-db52c343540c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2d45a971-8d1d-4165-bf75-1eec83d4a35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '(Tuỳ chọn) Mô tả quá trình học vấn' and (text() = 'z' or . = 'z')]</value>
      <webElementGuid>0dc6b97e-540a-4bc6-88d1-d2f088731337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
