<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lu h s</name>
   <tag></tag>
   <elementGuidId>f8a3c6c3-e63b-4032-ad7b-f4a041092bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go-to-next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#go-to-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>557c8492-cf85-4213-850a-380bbc3ab9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5b43c50c-6d27-4514-a3ad-10fa218b2f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-next</value>
      <webElementGuid>5747b054-2376-4f69-9d83-4277bb16d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary d-flex align-items-center font-weight-bold px-3 py-2</value>
      <webElementGuid>9f2c7dad-79dc-49f1-b1a0-a7122ebdcd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu hồ sơ</value>
      <webElementGuid>f1ed461f-f1a2-4e6c-983e-18824e12aa19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-to-next&quot;)</value>
      <webElementGuid>8ff70277-7eb3-4c92-89ab-0700409b1bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go-to-next']</value>
      <webElementGuid>8c99dcde-11b4-4e03-bfe5-0478ba91dbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/div/form/div[4]/div/div/button</value>
      <webElementGuid>d930f098-cc75-4b9d-b438-9687c9a43de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/following::button[1]</value>
      <webElementGuid>725d9177-fdae-45b9-b6f7-f495358e2848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Không cho phép tìm kiếm'])[1]/following::button[1]</value>
      <webElementGuid>d3f282a9-13e7-4311-a42f-496f5e7b0b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về CareerLink'])[1]/preceding::button[1]</value>
      <webElementGuid>89516bae-bbc2-44a2-95aa-da80a80b3590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về chúng tôi'])[1]/preceding::button[1]</value>
      <webElementGuid>8236a631-76f7-4aa3-bcd8-338f1b951e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lưu hồ sơ']/parent::*</value>
      <webElementGuid>7fc12b8d-186d-4e13-84ea-8482301f3601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>299c27a3-7d61-41d8-b862-3076e06d8ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'go-to-next' and (text() = 'Lưu hồ sơ' or . = 'Lưu hồ sơ')]</value>
      <webElementGuid>461c1431-46b2-4d26-ba2d-bb86b88cbb3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
