<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trng thi h s_checkmark</name>
   <tag></tag>
   <elementGuidId>98809cba-cd1a-45a7-b418-1b93a732c432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/div/form/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f97efba1-0c19-4fb4-86c3-336b05ac92c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>caed834e-63cc-449a-99e5-df16f034024a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/div[@class=&quot;container-0-2-51&quot;]/form[@class=&quot;search-config&quot;]/div[@class=&quot;search-config-option&quot;]/label[@class=&quot;fluent-radio&quot;]/div[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>8bbce76f-f9e6-4b4e-9d0c-c550e3f32e8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/div/form/div/label/div</value>
      <webElementGuid>1c2b52e0-3e76-46e0-beef-a352bb07715b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>66151933-0aeb-4c82-8422-4521f4d0fc64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
