<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_C th i ch_checkmark</name>
   <tag></tag>
   <elementGuidId>731d3ff9-5a5b-478f-8911-df3a7fc73559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[9]/div/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.fluent-radio.mr-4 > div.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b68c112-4df6-41dc-bd45-74e5a8a97ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>cb59a819-08c1-4c4a-b874-f561c478b937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;d-flex&quot;]/label[@class=&quot;fluent-radio mr-4&quot;]/div[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>9ed01f91-ab19-4ed8-af70-38eb9e84bebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[9]/div/div/label/div</value>
      <webElementGuid>a8dc40f8-4d8d-468f-9e6d-cf562a6a8833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/label/div</value>
      <webElementGuid>3a194de8-21e6-42a2-9767-480c479a192f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
