<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Sinh vin  Thc tp sinhMi i lmNhn vinK_253329</name>
   <tag></tag>
   <elementGuidId>73b70dae-2219-4f4c-b4aa-65fb10c3c6fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[5]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bcf4fac1-687d-433a-9bec-7571f892f035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>89bc8ad8-4ee8-4f7d-88ef-75bcb23043dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fluent-form-control </value>
      <webElementGuid>411f27ec-5115-4aee-a6c4-c02b5334fe28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...Sinh viên / Thực tập sinhMới đi làmNhân viênKỹ thuật viên / Kỹ sưTrưởng nhóm / Giám sátQuản lý / Trưởng phòngGiám đốcQuản lý cấp caoĐiều hành cấp cao</value>
      <webElementGuid>d8a59850-82e2-4d53-9ca9-da661add69c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group required row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fluent-select&quot;]/select[@class=&quot;form-control fluent-form-control&quot;]</value>
      <webElementGuid>0f28e935-7e45-4584-8836-738465586b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[5]/div/div/select</value>
      <webElementGuid>4d57dbad-fa6a-4505-aea8-11734beacf8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cấp bậc mong muốn'])[1]/following::select[1]</value>
      <webElementGuid>c396cd9e-6ec8-4d38-98b0-eb40b51a29bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại công việc'])[1]/following::select[2]</value>
      <webElementGuid>3316ea9d-92f3-48b0-b3db-1d898fdd5835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngành nghề mong muốn'])[1]/preceding::select[1]</value>
      <webElementGuid>9525aa3f-f687-45bd-8577-0dc6e03b5e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm ngành nghề'])[1]/preceding::select[1]</value>
      <webElementGuid>b73ea74e-d48b-4038-99bb-f5e5ad2f42ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>e9b856f7-e3e0-46b3-807d-02ed65f0d2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '...Sinh viên / Thực tập sinhMới đi làmNhân viênKỹ thuật viên / Kỹ sưTrưởng nhóm / Giám sátQuản lý / Trưởng phòngGiám đốcQuản lý cấp caoĐiều hành cấp cao' or . = '...Sinh viên / Thực tập sinhMới đi làmNhân viênKỹ thuật viên / Kỹ sưTrưởng nhóm / Giám sátQuản lý / Trưởng phòngGiám đốcQuản lý cấp caoĐiều hành cấp cao')]</value>
      <webElementGuid>5218d361-93ea-422e-bfba-4886e3371619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
