<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_x</name>
   <tag></tag>
   <elementGuidId>e6aab510-d4e1-4f1c-b569-5a9d4341a5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-edit-container']/div/form/div[5]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cd4d2a85-93c9-4191-b8df-9a2282ed449f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b37b2ac-d964-4836-b25e-7f645dc99faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>52a9f108-75a6-4725-9a07-de732086dad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(Tuỳ chọn) Mô tả quá trình học vấn</value>
      <webElementGuid>8944d84c-767c-4714-a9f9-5a28a3017c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-2-11 form-control rounded-left </value>
      <webElementGuid>ced83491-10a9-4356-9e63-c32aea57a813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>752edb7b-2601-4e87-9c9f-2098a8bebd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit-container&quot;)/div[@class=&quot;d-flex flex-column align-items-center&quot;]/form[1]/div[@class=&quot;form-group&quot;]/textarea[@class=&quot;input-0-2-11 form-control rounded-left&quot;]</value>
      <webElementGuid>9cefd1ee-0efd-4851-8134-d84ed595675c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-edit-container']/div/form/div[5]/textarea</value>
      <webElementGuid>08f6a4c4-7b51-4d3f-9416-272029107a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quá trình học vấn'])[1]/following::textarea[1]</value>
      <webElementGuid>185d43f4-50e5-4fdc-be6b-dbb27412a4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày Kết Thúc'])[1]/following::textarea[1]</value>
      <webElementGuid>19bb812c-9a5c-4111-90a4-f19f26f4e5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưu và Thoát'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e5f8c54f-96a7-4d78-9e46-1d9651326fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/preceding::textarea[1]</value>
      <webElementGuid>396ca469-8760-474a-8e9b-b582d752b61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>64df1dc2-7cef-4539-8c7c-929917258824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>00361ef5-b3ea-4889-8c5f-7a1d7d31408d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '(Tuỳ chọn) Mô tả quá trình học vấn' and (text() = 'x' or . = 'x')]</value>
      <webElementGuid>232ca8de-a0ce-4c6e-a441-21ad05c63734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
