<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chng ti va gi li link kch hot n email_ae56e9</name>
   <tag></tag>
   <elementGuidId>c1084b18-dcb6-49cd-9dfc-2016572a2add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd645cb7-9990-4b0c-a8af-d909d23987bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c0220ed9-4987-47bd-b40c-247c04410a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control password</value>
      <webElementGuid>0916a912-9128-465a-af53-6404e074a2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>dcb18f47-e7b7-4631-9977-54601b6b76ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>098ff05b-2ab5-4d6b-8683-aa24103bdad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_password</value>
      <webElementGuid>982daaff-a22b-45e6-bd40-b783ae308b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login_controller login_index&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6 p-0&quot;]/div[@class=&quot;login-form p-md-5&quot;]/div[@class=&quot;card mx-auto p-4 shadow&quot;]/div[@id=&quot;login_form&quot;]/form[@id=&quot;login_form&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control password&quot;]</value>
      <webElementGuid>f56d9126-ed2a-4fab-acca-3a9ada11dbbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_password']</value>
      <webElementGuid>c6723de3-c835-4e91-80c1-b5e45cdbf5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[2]/input</value>
      <webElementGuid>f6e06329-e0a8-41bc-a21b-e2afcc59934c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>71fff8c1-36a6-493e-b4f5-492225ac1ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Mật khẩu' and @name = '_password']</value>
      <webElementGuid>3f563c7b-2a63-421c-b1f5-2cc1bcc09676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
