<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T kha tm kim ph bin_9bc94b5a-4a22-450_db1fd0</name>
   <tag></tag>
   <elementGuidId>c75d5658-e6a1-433f-a4e2-f2915a2c0e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9bc94b5a-4a22-4509-8ffc-27ec8f2a3ffe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9bc94b5a-4a22-4509-8ffc-27ec8f2a3ffe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>695957dd-b4e8-4e86-bbe9-2865196a6132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1205993f-201b-49da-85fd-ebe233f322e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9bc94b5a-4a22-4509-8ffc-27ec8f2a3ffe</value>
      <webElementGuid>f3c319ce-00f7-4727-bff1-00fd77a37cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75712c68-672d-4250-80f0-615f27e82a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>82bc7f37-c328-4190-8ffa-60795fb96b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e315681-e99b-4ff7-8b4a-e18ba33d89f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c754b153-1670-4230-a2fe-3c01344721a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>71e0d9f9-764b-49c1-9dcb-4206a64fd6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9bc94b5a-4a22-4509-8ffc-27ec8f2a3ffe&quot;)</value>
      <webElementGuid>728335bc-0ae4-47a2-a3ab-3ef045798602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9bc94b5a-4a22-4509-8ffc-27ec8f2a3ffe']</value>
      <webElementGuid>b19fd3ee-28f0-42d7-adfc-38cdb50b22e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div/div/div/div/input</value>
      <webElementGuid>bb40b18d-6f5f-4981-97ad-556683a1a83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>e203c60d-a961-4cfe-b3c5-57bd398e68c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9bc94b5a-4a22-4509-8ffc-27ec8f2a3ffe' and @type = 'text' and @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      <webElementGuid>d04cb11b-d4bc-48c5-a62b-ebd0c82b0d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
