<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_40e58c81-c61c-4a2b-8632-863_7c4f1c</name>
   <tag></tag>
   <elementGuidId>3a353e30-5e05-4616-b8ac-3d24c64bc9d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#40e58c81-c61c-4a2b-8632-863dc092022d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='40e58c81-c61c-4a2b-8632-863dc092022d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb2179ae-7528-4380-9a76-74076389bc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bb0816f-ca82-4745-8518-95a464c0c99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>40e58c81-c61c-4a2b-8632-863dc092022d</value>
      <webElementGuid>ab043379-7f8a-4404-a5e2-691fd19f0156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4be9d0c0-aaaf-4516-a6f0-d45ef6b29ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42d46102-79ae-4d91-ad2f-153826daa6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c035b4f-f279-406a-bff2-b3303201caad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>a53dcf15-c6c6-43d7-827f-c30369ac0369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0ee38c1d-883e-4606-b1b2-36cb8f92be9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;40e58c81-c61c-4a2b-8632-863dc092022d&quot;)</value>
      <webElementGuid>796bf71c-f2d9-4f41-abfe-84b4a279c656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='40e58c81-c61c-4a2b-8632-863dc092022d']</value>
      <webElementGuid>a1f35b72-a054-49f9-86bb-c33fb1565045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>3c83bbd4-fb1b-40e9-97db-bd55c2dda1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d71097a1-a556-4c59-ad8f-81a74c9e6387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '40e58c81-c61c-4a2b-8632-863dc092022d' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>d0ae9f8b-4ced-45ff-9014-a0034c356f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
