<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_078079b3-20eb-4ca6-9d3d-a20_9ecf02</name>
   <tag></tag>
   <elementGuidId>d4723119-73bc-4c21-bb03-23a143e98f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#078079b3-20eb-4ca6-9d3d-a20734786839</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='078079b3-20eb-4ca6-9d3d-a20734786839']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd0a4618-207f-48db-b385-048eaffbdcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4546b1d-6798-4874-8ca5-49d1215e3eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>078079b3-20eb-4ca6-9d3d-a20734786839</value>
      <webElementGuid>7e19edfe-78e8-4eaf-8163-c5f3994a415f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a8157c65-ef4e-4b73-9447-209221a5d7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c9d6d55-0889-43ae-9053-88e1691ec6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b3b9892-96ef-4423-8d1e-27692d887f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>b7d324cf-efe8-4407-9bc0-000291bee35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>212e54a0-5216-4716-a061-740b383e3b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;078079b3-20eb-4ca6-9d3d-a20734786839&quot;)</value>
      <webElementGuid>cd504226-d9e6-47e5-a41b-72fe13dd079e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='078079b3-20eb-4ca6-9d3d-a20734786839']</value>
      <webElementGuid>e3d9a2a0-8452-4c84-b182-e626111968a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>69964a3d-b26b-4888-97da-548e982573d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d5593022-7b48-4fc1-8ebc-7eda11b3e718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '078079b3-20eb-4ca6-9d3d-a20734786839' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>1e6aa3f2-0aaf-47b8-aa3f-8c8dec120cf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
