<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T kha tm kim ph bin_97c1f175-a67e-4d6_07b6cc (2)</name>
   <tag></tag>
   <elementGuidId>42e565f9-fce5-49ff-a951-dc0a61c125a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#97c1f175-a67e-4d64-817b-87ab0c9d2cd1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = '97c1f175-a67e-4d64-817b-87ab0c9d2cd1' or @type = 'text' or @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7aec324a-cd6e-4db9-b22d-452c7f0ca03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>96c1c14a-867f-4788-950e-e62c269a4b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>97c1f175-a67e-4d64-817b-87ab0c9d2cd1</value>
      <webElementGuid>00140793-33d2-4ec3-ac32-cabe71b2257b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07b6f773-27e2-430f-88e7-5aa288841c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9f803730-db28-469b-988f-120e62a91c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d0dbeb9-48d2-4fc5-8d8f-aa4da3ccae12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea0ceb1b-bd4f-4fec-b029-f3c48dd04693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>d67ba2a1-6d3c-468f-8e61-47c5b8ebbea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;97c1f175-a67e-4d64-817b-87ab0c9d2cd1&quot;)</value>
      <webElementGuid>923de51f-c34f-4705-a3f0-c7e9eef5bea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22dc3471-3fd6-45f5-8bc5-5c734dd03bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>42a4c843-759f-4f83-bf1b-bcf77cd06a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>97c1f175-a67e-4d64-817b-87ab0c9d2cd1</value>
      <webElementGuid>6ecef7b1-13f9-4ecf-93c9-6f886e3f9f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c075b520-f081-405a-9b67-76da548bb59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e5cae630-9419-4434-a5e7-d1cc7a8d0dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0bcd13e8-b23b-4af1-8fe0-d52339f7255d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af71d6e6-c3c7-44c6-b24b-09c916063a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>78166ddd-ae59-4c58-82a7-4e493f40a931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;97c1f175-a67e-4d64-817b-87ab0c9d2cd1&quot;)</value>
      <webElementGuid>a45e8927-bbba-4a20-b240-00ecd8c88517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e30f5382-2a13-44ae-ab18-d45f30bf793a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e6c1c29d-ec55-4ba5-a4a5-c3bdd5add5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>97c1f175-a67e-4d64-817b-87ab0c9d2cd1</value>
      <webElementGuid>178bf30d-3252-45a9-b9da-c375c9886af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec915a77-0303-4eac-8fc9-4a118a368445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>671eedf9-03a7-42cc-843d-4579d99e60f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f73ff20-23fd-496e-8ee3-b6964d51f27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01516689-fbb8-4ab8-817b-1e6f0f65c594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>17f44cbe-28f4-4897-aad6-193a0537938c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;97c1f175-a67e-4d64-817b-87ab0c9d2cd1&quot;)</value>
      <webElementGuid>16f8a69b-5875-48fe-8545-2fefacb404d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5354c856-4108-47c4-9957-b92e220ea276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99853939-c9a6-41de-815f-07a0f149b79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>97c1f175-a67e-4d64-817b-87ab0c9d2cd1</value>
      <webElementGuid>65d36224-3252-4b33-b113-246083e768c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1f761e0-aa35-4f43-964a-3c171bdc3c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0080566-b08e-49eb-b341-b1b3ac1391ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c3cee8a1-f521-49e2-be47-bf9169b852db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5080246f-b366-44a8-a25a-091c773f9229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>9ca1bffd-1047-48ec-a3fd-9a502da814a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;97c1f175-a67e-4d64-817b-87ab0c9d2cd1&quot;)</value>
      <webElementGuid>6b450188-10a9-41c9-983d-006ec47537fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='97c1f175-a67e-4d64-817b-87ab0c9d2cd1']</value>
      <webElementGuid>459a09fe-82fe-408b-b7d5-97d1901f8f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div/div/div/div/input</value>
      <webElementGuid>54d9ef12-3df3-45bc-a57f-c0b9a003a64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>683521f3-f117-49dc-a36b-f01e8a0b2d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '97c1f175-a67e-4d64-817b-87ab0c9d2cd1' and @type = 'text' and @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      <webElementGuid>d067637b-7e16-42c6-9a25-5f669f2f2c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
