<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_fd1017d8-2cab-4a6f-963f-37b_4e7338</name>
   <tag></tag>
   <elementGuidId>e8defe33-fa11-4be0-9908-e8a250a6fb63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fd1017d8-2cab-4a6f-963f-37bc1a450c8a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fd1017d8-2cab-4a6f-963f-37bc1a450c8a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>853971cc-182c-4418-8d40-2428642b67b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdcbebee-42b8-47ff-baf8-e1cb74a30718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fd1017d8-2cab-4a6f-963f-37bc1a450c8a</value>
      <webElementGuid>c3221e0e-e897-44ae-9760-e824d8d6c420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cb0c5f13-91c8-430d-a9cc-f2440e2f4a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f0c1bca-f208-4307-b894-398acfec3621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9061907-83f9-4337-8cfa-f84b0f0ce862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>32143e9e-e6d6-4071-928c-638890a929f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8509f290-1c1d-4799-b10e-da50da2888f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fd1017d8-2cab-4a6f-963f-37bc1a450c8a&quot;)</value>
      <webElementGuid>08775cd6-b17d-4821-aca6-3cc98c30ac53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fd1017d8-2cab-4a6f-963f-37bc1a450c8a']</value>
      <webElementGuid>c0a0ab49-fb84-4e76-b959-60128ec40d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>6780c1f0-291e-4680-bec5-06ef5533c8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8ea062ca-a1e6-4bd6-ad3a-4b636be2d985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fd1017d8-2cab-4a6f-963f-37bc1a450c8a' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>ea7994d5-24f7-4f09-851a-c889d8f6c67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
