<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T kha tm kim ph bin_7a0195fa-ab47-44e_5630d3</name>
   <tag></tag>
   <elementGuidId>7abd9e2e-1783-4ccd-a665-78cc4d41b9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7a0195fa-ab47-44e4-a6ad-c4556228f186</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7a0195fa-ab47-44e4-a6ad-c4556228f186']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cdc0391-5637-43b3-bba8-27b9bcf95af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab8736dc-b527-4710-9ef1-dde6a3839df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7a0195fa-ab47-44e4-a6ad-c4556228f186</value>
      <webElementGuid>21096340-735d-4aaa-a8e3-a9b55f501e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82a62b7b-10ee-4b2d-9d84-5f6e5c64e6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>30260614-17cc-4d9a-a99d-fea3d7ee10d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>626e92aa-8f91-45ca-b866-08dc9bc6afb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6214407f-a862-4f43-ab29-fabcc65f4c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>3077585f-1f97-4435-a584-08af86fc0d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7a0195fa-ab47-44e4-a6ad-c4556228f186&quot;)</value>
      <webElementGuid>e73b6309-35ee-4699-ac09-8f6584e6591a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7a0195fa-ab47-44e4-a6ad-c4556228f186']</value>
      <webElementGuid>bcba0d49-572b-4a8c-9abc-9f771a310fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div/div/div/div/input</value>
      <webElementGuid>4c34579f-fa2c-4886-a397-04e1e39ab991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>407d596b-1e96-41fe-9e08-4362b2a5bd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7a0195fa-ab47-44e4-a6ad-c4556228f186' and @type = 'text' and @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      <webElementGuid>b58710b1-e63c-46a9-ba36-6d6d603c11de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
