<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T kha tm kim ph bin_3e4a3fee-9c19-420_985f15</name>
   <tag></tag>
   <elementGuidId>31122e33-5126-46a1-ad86-6a0af139e6c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3e4a3fee-9c19-420e-92de-5b06ea7cec5a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3e4a3fee-9c19-420e-92de-5b06ea7cec5a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f8a4252-c430-48b6-9574-f485fdd9e08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa839b23-84e8-4df8-88d8-d6354dde41e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3e4a3fee-9c19-420e-92de-5b06ea7cec5a</value>
      <webElementGuid>6aec6210-2c8f-4357-a75e-90972cb5f12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68605b57-c7a6-4a1f-a370-97a965ad7836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>10d5ebfc-5026-4271-be3f-092d240ca5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56a4aec1-cae6-42bf-be70-0a2aef17ad9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d50a2e18-67f4-443e-b135-aae9eb96e76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>1f6c38e1-c3e5-4371-a618-95f00bb01968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3e4a3fee-9c19-420e-92de-5b06ea7cec5a&quot;)</value>
      <webElementGuid>f37f80c4-a559-4b09-8f56-0e1149e3446f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3e4a3fee-9c19-420e-92de-5b06ea7cec5a']</value>
      <webElementGuid>45d6ee02-5df1-4394-a002-837c59734599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div/div/div/div/input</value>
      <webElementGuid>2003be5a-ca7e-4a01-9166-497e081eac97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>78232485-e7b3-4d51-ae20-6fea6e2bdfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3e4a3fee-9c19-420e-92de-5b06ea7cec5a' and @type = 'text' and @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      <webElementGuid>8ecdd04e-e7df-4d62-8695-2b2d3982e971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
