<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_4e14fb4d-1784-49d2-8dd4-e80_815c45</name>
   <tag></tag>
   <elementGuidId>64ea38a9-820e-49c4-9493-1bf64a72d249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4e14fb4d-1784-49d2-8dd4-e802883615f6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='4e14fb4d-1784-49d2-8dd4-e802883615f6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d0b5326-1ee8-44fe-ad5a-12ed81419157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72e2efeb-9cd8-4ded-b810-bc86c510b506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4e14fb4d-1784-49d2-8dd4-e802883615f6</value>
      <webElementGuid>0f4b12d1-511f-4d87-bc8f-c7f249d82eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0bdd12f-d705-4b99-b055-efa0448282e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b4575a8-3caa-49ec-bebc-af68a0960389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8333120-6479-4272-8105-90809dad7129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>4740fb25-7ff0-48dc-b35e-3ab7bdd3f9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a849d9b5-e935-4f09-a588-62e6d6fc2375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4e14fb4d-1784-49d2-8dd4-e802883615f6&quot;)</value>
      <webElementGuid>55b4b16c-55bc-4a5a-90c5-367d5ab0f6f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4e14fb4d-1784-49d2-8dd4-e802883615f6']</value>
      <webElementGuid>01aed8d3-2a5c-4444-81cc-11cc8585876e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>86a61221-d332-465b-966f-de6333053975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>274f9b4b-9e45-464e-819f-99dee37992c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '4e14fb4d-1784-49d2-8dd4-e802883615f6' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>e4f29b5c-31c0-48fa-9aed-d4bdd982895b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
