<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_688946f9-4f8b-4599-91c3-ab8_9a6068</name>
   <tag></tag>
   <elementGuidId>4e21ccf2-7bc6-4bdd-af9b-0de57b3cc7af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='688946f9-4f8b-4599-91c3-ab84448712f5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#688946f9-4f8b-4599-91c3-ab84448712f5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fd76d07-32cb-4d7f-aa76-21a69c6065a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef9927c8-7e10-4f90-a6d9-b0e717f9e7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>688946f9-4f8b-4599-91c3-ab84448712f5</value>
      <webElementGuid>d69276b5-3e94-458f-9ee8-5edf4b58e0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>60033955-0156-4357-9f0f-31c9dfab165e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>951ff15f-18c8-477b-8152-44150b4a996f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>767ddb45-a5c0-4419-a535-55e5c90bf384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>c4644dc7-e899-4f59-b556-c248c2070c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2a379657-ab6a-42d8-b0f0-c563e1c6a7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;688946f9-4f8b-4599-91c3-ab84448712f5&quot;)</value>
      <webElementGuid>9934bea9-9cb5-4cdb-8650-890d66c3bcad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='688946f9-4f8b-4599-91c3-ab84448712f5']</value>
      <webElementGuid>1281a03e-4cc3-4bfb-83f2-72e3c0369a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>f4b7d024-2ef3-47e3-a1b0-4100c506c4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>1010b766-08d5-4eef-8d16-3f92ab20f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '688946f9-4f8b-4599-91c3-ab84448712f5' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>ac3f1f5a-fd90-454d-ba26-6982aef76f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
