<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T kha tm kim ph bin_ad72c953-b271-4e9_45fc87</name>
   <tag></tag>
   <elementGuidId>3ebbf3cb-512d-4122-a159-eb168f52d936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ad72c953-b271-4e90-bd5c-48675a8399ca']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ad72c953-b271-4e90-bd5c-48675a8399ca</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e5d1475-82ca-46c0-b04c-617d3ba43aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2fb16f94-779c-4ebc-aca0-ba99cebc5a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad72c953-b271-4e90-bd5c-48675a8399ca</value>
      <webElementGuid>a957bb66-6287-49fe-8308-aae255208f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69090568-aa39-4a8a-b9b3-0c5445b83880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cf8b3e87-6532-4dd9-bcd9-0ab0a5e7f0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae215326-0cd4-4b33-98fc-e8b1e05a42de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4214fb9-78df-4fd0-b2ed-b92e8b3af7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>801c45bd-3ef0-4f3d-b3ca-90097b9262e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad72c953-b271-4e90-bd5c-48675a8399ca&quot;)</value>
      <webElementGuid>485371c3-b539-4ebf-ade5-d9e2c04d6a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ad72c953-b271-4e90-bd5c-48675a8399ca']</value>
      <webElementGuid>c37daa4b-a059-4c4e-97ec-bca4bc018398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div/div/div/div/input</value>
      <webElementGuid>cbb3ba43-a0b2-436b-b4b6-3d6a1830c0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>2f83f4f5-bb06-4ab6-847a-e7b7c0ae8e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ad72c953-b271-4e90-bd5c-48675a8399ca' and @type = 'text' and @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      <webElementGuid>4bee9b78-f48e-4329-a909-090fba85e50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
