<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_d7fcecbf-d095-4216-882c-1c2_bfd61d</name>
   <tag></tag>
   <elementGuidId>8a8e6a99-c8f1-4bb2-9dd1-1dfba58c0110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d7fcecbf-d095-4216-882c-1c2c5d8d94ad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d7fcecbf-d095-4216-882c-1c2c5d8d94ad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d53bb4f2-3501-434f-839b-4bfe6a16bb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fbb8744-d458-417b-9773-2d1534c34f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d7fcecbf-d095-4216-882c-1c2c5d8d94ad</value>
      <webElementGuid>5f530866-f5a9-45b7-9551-91764d7e9bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>192d35f9-243b-4d56-8a30-c0e40d99c10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>773e5561-bef2-4329-a068-13bf49f04a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4494f602-e1ed-4d3b-821e-fd1317d67eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>8e05b31e-d9bb-43a5-bf6b-8fb992be2e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>13861e0e-d22e-4790-a9ba-35e14c25932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d7fcecbf-d095-4216-882c-1c2c5d8d94ad&quot;)</value>
      <webElementGuid>588cc3f0-7e72-4cb3-bc33-6ad92a8d4e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d7fcecbf-d095-4216-882c-1c2c5d8d94ad']</value>
      <webElementGuid>f3e6661c-9377-475b-99f1-6a8b5d4e09c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>63c35110-173c-484f-a61e-3cdd3b460977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>444e17c3-f52b-4c2a-b17e-c966a9566eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'd7fcecbf-d095-4216-882c-1c2c5d8d94ad' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>e66c8957-ae1e-4398-b7fa-204be4849808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
