<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_cb4e4e42-cc9f-4222-8c4a-41a_525084</name>
   <tag></tag>
   <elementGuidId>383305ad-7255-414d-9e37-ee3c6d1aad62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb4e4e42-cc9f-4222-8c4a-41a0c85bea66']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cb4e4e42-cc9f-4222-8c4a-41a0c85bea66</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f23a2d42-e672-459a-b9d1-4389bc17a475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc874c14-4cd8-4d5a-ba10-1141eaeb8f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb4e4e42-cc9f-4222-8c4a-41a0c85bea66</value>
      <webElementGuid>2f5eeec3-290f-4df2-bb1f-831cec107a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a07b273c-c942-4be2-837e-d38986990abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b792a1c8-ca63-4bd1-8172-45c438da490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd848599-959e-464e-872f-183221041031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>085c4607-5be0-4af2-9271-ac10345a359e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ad73b685-2148-4a79-89fb-0dc4fc2057bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb4e4e42-cc9f-4222-8c4a-41a0c85bea66&quot;)</value>
      <webElementGuid>92abc5fd-53d1-483c-ba83-0f2f43fb7bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb4e4e42-cc9f-4222-8c4a-41a0c85bea66']</value>
      <webElementGuid>a600a2c1-8e47-4649-ad79-c78ebb6167fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>d0d75b91-43d2-429d-81fd-9c6f8557df4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>c504e41f-ecf4-43a8-8264-2c92be0ca63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cb4e4e42-cc9f-4222-8c4a-41a0c85bea66' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>913785b1-e242-4485-a6aa-921ae7024731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
