<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_c877160e-362b-4549-be04-c26_bd497b</name>
   <tag></tag>
   <elementGuidId>37f00737-57b8-4b50-a8a2-12dc6a98d138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c877160e-362b-4549-be04-c26abc35e374</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c877160e-362b-4549-be04-c26abc35e374']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac4dd3a2-6ef3-459a-b4d2-1c675aa11cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f661ba39-eb6b-48ea-ab07-8f8b238a035a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c877160e-362b-4549-be04-c26abc35e374</value>
      <webElementGuid>37899ce8-f63c-49c3-99ba-874c55d0343d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>48c492b1-07a0-4cfc-9193-76409964ebdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79ab2ba6-fba6-4f8d-baf7-e6282c0768aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a8c5bc0-5855-4efe-af13-f0a4c05c07dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>ab403571-84a9-4750-a24c-572816f5fe08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e2ce58cb-1899-42dd-a5a7-276f5f489bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c877160e-362b-4549-be04-c26abc35e374&quot;)</value>
      <webElementGuid>607b2aee-59d0-4c04-92e7-e66df9d62922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c877160e-362b-4549-be04-c26abc35e374']</value>
      <webElementGuid>08bd6e48-ee13-44d0-b2b5-16edc1cac6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>5a20ec81-0a98-44e7-b43b-fd0619b9eec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>107603e6-6cef-42d2-acef-00f7af45d159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'c877160e-362b-4549-be04-c26abc35e374' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>eb5cd023-45f2-40cf-8ab1-3f2ba371f81d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
