<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T kha tm kim ph bin_0e5244a1-fc39-406_d8166c</name>
   <tag></tag>
   <elementGuidId>0c751bdb-7fc7-40d9-8cb6-6bf4da78cf02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0e5244a1-fc39-4068-83a7-78291f339050</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = '0e5244a1-fc39-4068-83a7-78291f339050' or @type = 'text' or @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bda4f18-a6f5-4884-883a-41597115212b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>88529a3b-8027-4723-9a7d-4deefe128dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0e5244a1-fc39-4068-83a7-78291f339050</value>
      <webElementGuid>67da59eb-9b24-4ab0-819b-9443f1573dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12f23c57-f2a3-4d13-b17c-5d5786ab4faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>abc12d8e-0ac5-4cd4-9161-ebe5df7c43f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9c4d77d-bbf5-4a34-95a4-d6876fe39d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cfb4be1-5d91-414f-99d6-46ffb3396957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>0c6eab23-8ff6-4e72-9482-de2dfe52dbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0e5244a1-fc39-4068-83a7-78291f339050&quot;)</value>
      <webElementGuid>0047b25d-64ec-4d4a-bb03-669357899c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85eb4791-37c5-49a8-b542-6c82a7a6f44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d23b9f93-b705-4fa3-b801-f4492a60f306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0e5244a1-fc39-4068-83a7-78291f339050</value>
      <webElementGuid>4c38a062-3754-4a0b-8820-4c7d81e95de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>995a4a79-37ed-44aa-be8d-a1619697c1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f0efd7f-db9b-4906-8582-5cdd9a9d69ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8449c737-c38e-4514-b62e-e1a4344da1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0f77cdf-5f11-4a6e-a71e-9b1e2f5114cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên vị trí, công ty, từ khoá</value>
      <webElementGuid>21fbe77d-4042-4c86-9b06-0a084c0fc8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0e5244a1-fc39-4068-83a7-78291f339050&quot;)</value>
      <webElementGuid>f9c2f534-f7a8-41e1-a618-5cd92060ef56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='0e5244a1-fc39-4068-83a7-78291f339050']</value>
      <webElementGuid>1a359524-9f9b-4f95-8f41-c2a9a0cbaa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div/div/div/div/input</value>
      <webElementGuid>322ef63e-b106-471d-a11a-7d73f926e363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>a05e0a1e-bbf6-40c1-bb5a-48b26b792896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '0e5244a1-fc39-4068-83a7-78291f339050' and @type = 'text' and @placeholder = 'Nhập tên vị trí, công ty, từ khoá']</value>
      <webElementGuid>fc7c1176-af41-4209-9336-e2452896d5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
