<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_1499df32-4315-4e74-afc1-674_d71148</name>
   <tag></tag>
   <elementGuidId>c6391ff7-86ee-42ec-9d58-ad541af680e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1499df32-4315-4e74-afc1-674bc7ede130']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1499df32-4315-4e74-afc1-674bc7ede130</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cab4f5a-fe6d-49a8-b36c-218ada539f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83d96c8d-e260-416b-b0c4-0b4fc669e243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1499df32-4315-4e74-afc1-674bc7ede130</value>
      <webElementGuid>ffb73f68-bd9f-4c2b-95bb-b71aa3bc3bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>404e02e8-855d-44c8-88f2-14954f79b68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a5cc82a-a296-4546-ae2b-4472e3deae8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05ed15be-9aae-498b-a0e9-65b0de39500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tỉnh, thành phố</value>
      <webElementGuid>19cf175d-4b8a-4c61-a9d3-319f5ddd09e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f048ba9-a254-46cc-a2b2-5e0c6ddb5d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1499df32-4315-4e74-afc1-674bc7ede130&quot;)</value>
      <webElementGuid>edf577be-e734-414a-a7ea-1d5667c41504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1499df32-4315-4e74-afc1-674bc7ede130']</value>
      <webElementGuid>da2fa236-83c5-48b2-99b0-319aaa406390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_nav_search']/form/div[2]/div/div/input</value>
      <webElementGuid>ad8a0b6e-1cca-4242-aee9-671a2b48e36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d91496bb-6feb-4d27-8b14-f74a19fd9534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '1499df32-4315-4e74-afc1-674bc7ede130' and @placeholder = 'Nhập tỉnh, thành phố']</value>
      <webElementGuid>249229f6-c9b7-4719-8b4f-09db30e9c15d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
