<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Bn tm_lni lni-pencil</name>
   <tag></tag>
   <elementGuidId>c5cda1e1-d891-4495-958e-790daf95842d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.lni.lni-pencil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6d91e6bf-6d54-4e5f-a7fa-9dc64b9ac866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni lni-pencil</value>
      <webElementGuid>1ba19cee-f980-48c3-a0e3-a1f50245f56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;my_careerlink_controller my_careerlink_show_resumes job_seeker  resumes-loaded&quot;]/div[@class=&quot;container mt-lg-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 px-0 px-lg-3&quot;]/div[@class=&quot;resumes-container&quot;]/div[1]/ul[@class=&quot;list-group list-group-flush&quot;]/li[@class=&quot;resumeItem-0-2-8 list-group-item resume-item position-relative px-lg-0 py-md-2 py-lg-3&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-body d-lg-flex pl-3&quot;]/div[@class=&quot;resume-action d-flex align-items-center ml-auto&quot;]/a[@class=&quot;resume-edit btn text-primary d-flex align-items-center justify-content-center p-2 mr-2&quot;]/i[@class=&quot;lni lni-pencil&quot;]</value>
      <webElementGuid>098f3eda-c287-4696-82c3-d840d4886dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/i</value>
      <webElementGuid>22d6ca80-421b-4d88-ac0e-ba5872f81fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
