<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Vic lm ti H Ni</name>
   <tag></tag>
   <elementGuidId>4909cc02-a78d-475b-af9f-15fd1fc91ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng trong'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.px-2.px-lg-0.search-result-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4fb1cc6f-8f32-44ff-90b7-6ce781b348eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>fbd21b1d-a2f9-4f82-a57c-7c52b6cff155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>86aa758d-c896-41e1-88a8-9d4a894957d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>8317e283-6f3b-428c-b3c9-759e239bfe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0ad568eb-c906-4c8d-89fa-4d9063c08661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>59538aec-69c8-4110-9b9e-dba11b2fc3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>dfcf213b-d826-4d19-bf73-6aa9d7134194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>8edb86b4-bab7-492d-8f3e-5d213c36167c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>fc01c3a2-9352-4789-8e9e-7dc62edd93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>42e90dd4-830a-424c-b82e-3556dfd415b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>8ac5c9b0-7df0-4b82-a30f-36088cb3b50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>edf50f67-9df7-4374-9bc7-710f1e2f8d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4850215a-ba23-419a-82ea-ec6088845a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>eaef3ca7-f340-42a0-b3e6-844867e072e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>4e0626b5-13eb-43d1-b729-352015e195dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>9b14c51f-1fc8-4325-86ab-ede9ffaeb9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c0e589ae-a3d4-465f-862b-7ab590b81e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>90849d65-bdcf-4725-a697-7d475bd82624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>f6c6763b-1691-4468-8b9b-408b606d2ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>9fd69470-c971-4521-93d3-fe879faec067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c47d33f5-06f1-43f5-9259-e382143c2983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>9212f750-3249-4eee-a56e-b6b59bcacb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>ceb208c8-3ae4-4401-af35-c7067e934ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>77f3e5e3-3385-4fa8-839b-152aa17644fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4fa35cca-fa65-4b10-93e0-777a0ae5a74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>87980f21-c71c-414b-a9ce-8cb151cb7a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>1c3bd9ee-a4cc-4a31-a040-d4257b640613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>9391d337-c18e-4ae4-a169-ba4360d2db68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d3bfbca0-248d-4c47-a5d1-fa78d285f2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>5cff95e5-f574-46e2-a87c-fda64c31feb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>a1b3028e-9338-4f38-a6dd-7d6be9c6b8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>035ec1f9-2d65-4d16-8e61-71bc38c5e8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>dd19c0de-01a4-4e20-b2f9-ed63c85c245b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>2896c572-867e-4058-936c-0d3d68dc6a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>64805019-3aa2-4ec0-8d65-50fca08e6122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>869fe7e7-7dd3-4584-a5c5-300a667f1097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ae3f81b6-637f-4147-999a-df313e9eb713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>b3104394-1de3-4158-a775-40860059b09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>60e0e40d-8767-4b38-a24a-33e9b1e9b9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>3d28377e-6bd1-406c-85a7-cab92d9a0d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0c993a67-1982-4d0b-afba-649caf04b747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>3fb4a13d-6dc1-4c9e-be71-fce891d39ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>f7cf6937-dc6a-420e-bf89-8fef5d0329af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>13cfc8d0-0451-4025-b791-87e88ac0ad73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4d352a5b-9c21-495f-b36b-c8ab36778c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>9c9cea57-00dd-49d2-bef9-b2e416a027e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>669d710e-735f-4abd-832f-4e8e263f362d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>3ecc5fa8-f878-4dbb-8b40-597b25f67705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>65a33efb-1be0-4b90-ac6c-95b8506aa5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>61bcb56c-2432-4eb5-b73e-03899c6e0e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>4e8ec858-49ce-4b8d-b671-6ab5314653b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>7261828d-c03d-41d2-932f-8d3dbd5d8895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>68325c8c-b166-4c70-9902-b529b0fb297e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>feb3a3c2-47ff-4037-b8cc-0b54ac7a16db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>6cb1b372-9d0c-45fc-941f-cdb2cfce582b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>d8f2a992-0cc9-4521-8b34-14c2822842b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>217d4662-befa-4108-bcb3-a3bb85b0e26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>7bb5e739-5396-4f2a-8638-6120f1f7a8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>98f1270e-4a19-41d5-b752-ec9ce76c9a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>2d486945-0c0d-4ebf-9e03-9bc2e0e200e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>81efefd9-06f2-45ad-be1e-737a61d11c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>e639fc27-ba7f-40cb-909a-2338911b87aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>6466a6fc-cac9-4e2a-9aaf-8f8d61b2784f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>0e4e3004-9418-4ecd-918a-6b10e07222c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>598e3000-cbde-4ea2-aea8-339c42ba70d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>19bf0265-eb3d-4784-97ac-003249c9ef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>2d19b31e-97b9-4e29-aabd-5f713db12a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>0b30aa96-15dd-4f33-b822-6a7691b46254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b708436d-2502-467c-8ce8-3404abe1d50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>7b0f5a98-3cde-44e8-9aec-353f7e337526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>50b3a360-22e3-4413-ae64-fcfd7b93c6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>de0fa466-56bc-4e8f-8f3f-81476bb7743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>63b13582-aadc-43cf-b6c2-60772959865a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>ab34e529-4e11-4690-ba5c-5e550208fad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>8f197eb7-9e61-4bd5-97af-5cd094a24586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>57083292-7370-47a4-873b-d3f2d91a1dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>24bad158-311e-40bf-b291-bf6a2f71ec4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>57bb1021-567e-4d79-90af-32a1814f7ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>9dc74437-b986-404f-a08d-0902b4e91032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>b23e9702-9359-48d2-8f73-48fcb5a09fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1d893716-c706-4db6-b8d3-43807a637d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>568fed2f-dc18-4f47-be0f-7df2e784a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>04730591-0789-4ce7-babc-da2ff742eb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>ae5da193-a0dc-4b6c-a2db-808d00d9155f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>28e45c7f-ee09-4b44-82fb-b946caf33963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>d7c48950-8689-496a-ac2e-69e898a86668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>7bbfe02d-e671-4cbb-bb9e-d92e082d9906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>9c3dc150-9567-4596-96fc-8038efe70629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c527fb7b-0ea6-430c-a084-fe316c2197b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>4d7fb1a7-0f2d-4df7-a139-d89381e209cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>8cfbdcb1-b911-4397-8fd8-3f569717e59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>1760175e-181a-4c31-b371-2f1f07d293cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1ce35046-a144-4b64-9083-047651d211e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>6f348ee9-69a5-47b5-92fb-1cb325c99c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>6d1b89a3-fe1b-421e-91e6-f062d3b606c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>8042fd82-3a8f-4345-a7f4-b9350f90a059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng trong'])[1]/following::h1[1]</value>
      <webElementGuid>2c1ce12a-dbd2-4f50-937e-e090a320cd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại công việc'])[1]/following::h1[1]</value>
      <webElementGuid>2f92f139-277b-4c95-8e25-e5b69160d5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mới cập nhật'])[1]/preceding::h1[1]</value>
      <webElementGuid>f3733dac-d49d-41f9-a180-0b895a641d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mới cập nhật'])[2]/preceding::h1[1]</value>
      <webElementGuid>66bf9bbd-e873-42a7-a83d-5449be9521d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Việc làm tại Hà Nội']/parent::*</value>
      <webElementGuid>60e1052f-2ab4-4d9e-8ac2-085511eb248b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f149e527-939a-48be-a676-7c82f1d069be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
Việc làm tại Hà Nội
' or . = '
Việc làm tại Hà Nội
')]</value>
      <webElementGuid>3301abdc-5e1c-441a-bdc8-cf73054d6cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
