<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Vic lm ti H Ni (2)</name>
   <tag></tag>
   <elementGuidId>975777fe-9027-40cf-a690-3991567dde1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.px-2.px-lg-0.search-result-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng trong'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e97376ed-6a4a-4ac8-902a-774425455b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>86cfd9b5-16a8-4020-b912-d30a5ec20edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>51245218-f631-4140-8c56-77b61c381970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>d8cbc530-74a7-4053-bac6-ad77dca2052e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e810ffe9-f68d-448a-ab8e-5b5ff5030d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>8290c718-c353-4baf-8ba5-8ddf5333bcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>7d24ae7f-7d27-4706-9f94-19642edafd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>02766baa-378c-4ddb-bc85-7df38b978708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5d29f660-39a6-4867-99b2-82697626f967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>8b37ddc0-1204-4451-88bb-30d0911cae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>af4b6a75-6e23-4c0d-8b82-c254f1203775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>9269cd37-cf8b-4206-8b14-502ed9c7b7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>996eff00-94aa-4596-8465-20fc8c7f989f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>b7b484ed-ed9c-4ce4-a7c5-0d368fa3144e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>6a4137fd-e535-4d06-ba6c-808a2f940d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>d01dd0bd-9d51-4df8-95c4-2a0058401eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5620ccf2-b708-4dcc-aecc-e290a6994644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>49c5bb2c-7903-41c6-8732-9314b911d91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>5b1c95e5-26c0-4eb7-b663-fcf476aa6b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>54190801-5802-45ce-85f2-b5f4c7bfc77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b0cfc907-5f20-47e7-8863-fdb091d4a03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>3728477d-f85b-472f-988e-13f32d9ff14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>43dd5d40-ee28-42b8-86de-2deb07d0218c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>5faaf9f8-26ca-4661-8d6a-2e774bcb7bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3f9a1f32-6a4f-4cda-a975-8fdad3804999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>8a43f6d2-e611-4bb4-a749-925d0685c2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>e529b469-3a85-4856-b3cd-2d2e9cd8287f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>d3ebac36-e85c-4280-ab97-addbd5a2f57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a0ddb3e3-9137-4ee9-8e2b-8db4af20e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>4262af8f-6928-4721-bbbc-8f7d72c2c465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>88c3203c-5f97-4f82-b30e-ee9f4ec1cdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>646dbc2c-7011-4f3d-9d70-1d1ec0240f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>585698cc-7298-4cba-90c1-3edb864aa570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>4f015291-672a-438d-b58b-e973377df131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>962cd0ee-173e-4d67-8d35-9a20b3829277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>55007215-f770-404c-a516-7bbead5859c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>feb08cd0-2350-418d-8e41-08b6f70fc4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>7d47504d-0c6c-41a0-b772-2867dc92b236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>5239a5be-f677-4a88-8bb1-cf0b10269527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>4d2078d7-53ce-4060-98b1-7b4b1944b398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4ad678b3-fc07-4316-83b4-045c531f632c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>9191dfc9-e0cc-4b15-8f44-5c377a949ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>5aeb143f-b984-43f4-b030-11e605820881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>1273af13-52ff-4dec-961d-7f79b8eb2eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>02f6d4c7-b20e-409a-a078-2f2606fa1b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>92438c44-8e48-45ab-9a92-c44dba778b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>e08e3062-e6d5-4aad-ac78-9afec3a3f023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>3635462b-93d8-4e92-9f8d-0e54e8100cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>385eb753-ac7b-46a1-8619-bf8e1adb38a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>6492687f-0edb-4430-99a8-d6871f5184b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>b1011aa5-e9b0-4fa7-b326-91eb92d76f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>d55fcf8e-5ffc-4064-b3a0-d93788d8c99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9fb973a7-e6b8-42e4-8fca-48929201a287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>b8a630a9-1a40-4e64-9135-0eef063e13f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>15c2ad01-4209-4a83-9bd4-4a31c33b91cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>23c54904-c0f2-4efb-8472-461faaa32a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2318bf17-d9e8-4f77-a4cf-949b96c7c909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>1c47dc02-03ef-48c8-b798-9fd063754b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>200b6c49-a6d4-43ba-af8a-0fc53d000523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>aa68d3ca-1118-4335-8c4e-5f7dacce28d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f13df6b8-c338-4b7f-a659-17f5ac1f922b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>c43e9a0c-b320-4512-91eb-45b6e3b028b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>7ca00578-2797-4e65-b9b4-ebb498774094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>e07a5fa1-1181-4c54-9ee5-7aceaa8631c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>97a79406-c601-4dcf-aad6-2420f9be0815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>86d208d3-c945-41c1-84f9-89150dd674b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>e8283267-ac1c-47ec-b289-1a326aace604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>6c7d6465-cf0c-45b7-98f9-5feb468cb1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>76cfccb1-7b31-446b-b392-799af9b68c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>12dbc951-2470-4c25-bd3f-d67d58b4a174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>a6b2f5d8-595a-435a-8849-895dad4a4255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>a2f42da0-30b7-4d20-ab1d-86e5b7c54d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f167d07d-97de-430e-9f78-dc3506b25875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>12215b2c-67e1-4fbb-b964-9a33864aebc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>2bbdfdbd-b612-4b6d-a83b-fc63a8b6f576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>7e4e0362-75d7-4a08-98cb-a63ad7599d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>329fba58-cbf4-419a-93e9-938d6abe58ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>d7f4b0bc-c794-45e1-8ac5-92a3cdb23739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>977bfc80-71e7-40db-95f5-86b8200de924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>6809a0d0-6d08-4190-ac10-12763be4d378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0271c03d-af28-45c7-8f91-eec401f8c9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>60642978-617a-4ad0-89ab-f138d9bf83ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>2701969a-3b38-44dd-9f73-6a92b767a7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>705801a1-9e20-46f1-98ae-e7b503d9ff67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1f01a061-079d-4749-a9f4-81478cfe8345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>83f34e73-8730-4a7d-b1b5-4a9017bf8673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>f49a68df-88de-4149-88bc-315d1e53b168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>b2ee0206-4053-4ab8-b4ff-bfca18607b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>151ace8c-4890-4537-a8a2-bd67e282b911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>239ff7f2-2f8c-428a-a6aa-36f8967e9996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>31b31045-317a-4811-aa0d-3ed223c14b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>aa3fe633-08c6-4ca1-8206-bad5833327b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>206cc48a-b887-4186-933d-ed78d5964f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>b44fd9e7-d7f9-4fd4-a27b-47578e27dc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>2138aee3-ec11-4d02-891a-e10e2dc0b5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>12aa10e5-0f3e-4df3-bb52-c722a64ac947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng trong'])[1]/following::h1[1]</value>
      <webElementGuid>d4e1f779-4272-4acb-9ff5-521e2bf77927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại công việc'])[1]/following::h1[1]</value>
      <webElementGuid>e17cbf80-4c94-4194-a97b-c955e7477035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mới cập nhật'])[1]/preceding::h1[1]</value>
      <webElementGuid>692741f8-c6c7-4eff-a93b-eac0de658af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mới cập nhật'])[2]/preceding::h1[1]</value>
      <webElementGuid>e6029971-062b-4759-ba25-0f3a96e19ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Việc làm tại Hà Nội']/parent::*</value>
      <webElementGuid>91184e06-d30c-439b-a7a6-90f99f221dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>28178c90-4c7b-4cc8-bc4d-4927b31bda79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
Việc làm tại Hà Nội
' or . = '
Việc làm tại Hà Nội
')]</value>
      <webElementGuid>3884e651-f6a2-47d6-b8c8-41ebc80b998a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
