<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Vic lm ti H Ni (1)</name>
   <tag></tag>
   <elementGuidId>8f62c1b8-419c-49b3-bbf1-3bf863e935e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.px-2.px-lg-0.search-result-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng trong'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3f39e966-f6ee-4fbf-9b11-208c08cb4551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>caa1b81f-cf0a-45aa-b87c-0b9df1867baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>4a46b949-5626-44aa-8efb-c343dcde7ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>2a7266a7-ce28-43d8-87fa-f940e96d69a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5e75ff1c-8833-4617-96e1-cf777309d467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>73da1c10-fcd4-4748-9371-e0bc59aba9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>72b6b8d8-87f2-4ec5-abc7-1e866546531d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>6a0605a0-a420-422c-b5d5-9e0998d00636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>eeb9ef7f-021b-4f57-b51e-c3b403a089d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>dcb8c433-b333-43ed-8bda-13e2e3d653a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>188a2b8a-9708-4987-a1e2-a2c876bc43b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>4ec7c104-8870-4a63-a3d8-c34a3e884919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>db805be3-8f86-4088-92a3-318466b80f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>f8b9de26-f10b-4fdc-9388-f2ccb5c93cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>89f59c27-81ad-4d0b-bc9b-2a3fd9552d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>b6059292-3d8f-431a-ad78-a5c1762fa0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6f5963b4-0158-4899-86f0-11153763491a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>8b991dec-34a5-444f-9a18-f31f9147ba63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>237d514f-793b-4795-a220-af2664068d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>e7ac60b8-ba4a-43d2-a4f1-2ed66e125cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e154f8fb-025c-41ff-b559-a725c762d2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>2a597498-8716-4c61-b523-0bec1bb3ae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>d4e10554-32a8-494b-9667-d7e0629039b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>aeba1331-ffc4-4dba-b2b5-7d59736b7b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1e7be6b6-b862-4b5e-9d08-29276e8ad5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>752204aa-41c1-4c20-98fb-5f5a78a56f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>aacfa551-becd-4a45-9370-187a23949fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>becf4a8b-f663-456a-8457-e7bc0c27971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c12634db-a69a-4d2e-9ca7-ff6f3d6a4e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>5fe81021-208d-4a89-8f67-8bed09507dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>ef60b5b2-065d-4ac8-abac-f9b4b105c3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>1d1d9a44-ae2e-4413-a00c-e1e5a6446537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2d644a3f-e225-4e0d-99a9-458ed648edf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>e97e5bb6-8c60-4f3d-9139-2248ffbf0d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>a0e5b996-bc97-4199-9b46-449dda5cbef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>37b70246-217a-4ca3-af8f-919361613031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b877ca7f-e1d3-4c45-bc92-1e775bfa7231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>ea83654c-25b3-46b2-a324-6eb0a70a0f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>c2435e2f-9ba5-4650-8965-8292751fea51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>0201357d-7697-4166-b85e-2bedeea497eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>806c57fb-db3a-41d2-a4d9-53f8875ef59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>26c33e8c-6d5b-4e67-a131-bb44efbf0c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>47b63d3f-131c-4a09-8671-eff82d093ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>a495cabe-f337-4a14-ba4d-125da4cfd30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f05e4b48-c1e6-42e4-859a-09a1bc1138a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>23c7af94-3c3f-4758-84cc-230f765d5abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>a9cc7d49-ff6e-47cd-9791-6b34e8b02abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>16891cc6-7ad9-4f55-b30f-08588aa379ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>425e106e-8731-4994-832e-8f656cd8051e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>5bc779a7-6e9d-4ed3-bcff-d25242917367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>5e028727-3cfd-4caa-8991-af1f6e85918e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>f0f52ec7-91da-46a3-aea6-8ca7a167b3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d00e31ff-7007-4de5-a21d-b990c5a4ac17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>7dbfb1b2-8c8c-4cd8-9cdc-772e6cebb4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>d3ebd5d7-7d27-4f36-a1d3-54989f2cb942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>0a1e86bc-4ebf-482a-a9ff-58f704fd0edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ff37239e-39b4-4d7d-ad93-da367ec14593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>c00328ba-21b7-4c15-a86e-60ff17573bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>aab1aad6-0b00-4eb2-95ae-08665bedc6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>5dddea2a-633a-487d-b10c-4922fe293256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9365c709-c403-4eb5-8319-d31b0b4db79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>773d6903-1641-46d7-a385-3cd7c25d3174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>23ec595f-a83d-4bbc-8103-661c90deed04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>1fd857b0-e26f-4c4d-9bf2-dcdb98b9f0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ffd059d5-d285-4b49-bf80-a2e812b5297c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>4a3b66d2-0a7c-45ea-bb10-e4c25bcc4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>b5f1cc29-c75c-4668-9ce3-1d70e9d1f4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>53e410a8-af96-459f-814e-46255a13973a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>26430647-0320-42d6-9863-e322005a1af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>fb927425-85c5-44a9-aacb-de14c718dfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>c4544ab9-33b3-4ed2-8df6-bb5466bd8a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>c606980c-7574-4bdf-8708-3d45058e7d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>353ebe11-fc82-4f8e-8e2b-426b051d7f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>afc15d5c-6eac-43af-b255-2b47c69a60a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>0432e0b6-39d0-4472-b73e-f8dc797c01a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>99a8688a-4eb1-444f-9485-633d3ed633bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>dfe204d7-de0d-49ff-963f-9bbee03b6c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>41734f15-73e5-4169-914a-0d52276553cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>12e208bf-cad6-476e-858b-5b533d4575e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>6e5a71d4-69e0-4ffe-a69d-84d67d67273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ffddfc88-dfb8-4ab8-bbeb-7f3f6b2edbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>379146e9-3e6c-4bdd-ae9c-dcb00237cb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>da223c43-cab8-4362-bb56-c6441420ff2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>e19fa02c-4f73-42fc-91bf-b2eee46da38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>cb22a022-859a-4cf3-8436-299353099bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>716858e8-460a-478a-aaf9-21ff812ff2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>2838c124-493c-4b0d-96fe-7a09631a8a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>83e8ba4f-3409-4413-b922-985320fe606a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>cd3a3adb-a5b1-40ce-80db-b84c192c5ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>77dd571c-0baf-477a-9fd4-1441f2f12b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>73e149b9-6c62-4e03-8d1d-57f65f4a3d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>d7052365-31a8-479d-93b2-f50a74febb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e1ef05c5-aa18-4242-9863-a5e5d9e64295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 px-lg-0 search-result-title</value>
      <webElementGuid>90346a8b-4dc2-43ba-98ee-9a7d55209e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Việc làm tại Hà Nội
</value>
      <webElementGuid>f91d31d8-acb9-4e1e-adaf-9e79c3f13e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobs_controller jobs_index&quot;]/div[@class=&quot;container mt-3 mt-lg-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 px-0 px-lg-3&quot;]/h1[@class=&quot;px-2 px-lg-0 search-result-title&quot;]</value>
      <webElementGuid>f1764681-e19b-428f-a797-336b4a00d180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng trong'])[1]/following::h1[1]</value>
      <webElementGuid>7354dc16-28ea-41fe-a2ef-5c113353073c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại công việc'])[1]/following::h1[1]</value>
      <webElementGuid>195073c4-7876-47da-8616-c71648420aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mới cập nhật'])[1]/preceding::h1[1]</value>
      <webElementGuid>94d837df-688a-4100-a0b6-e34bcd0537fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mới cập nhật'])[2]/preceding::h1[1]</value>
      <webElementGuid>b6f7307b-f2ae-4704-9cdd-14fe0c2daf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Việc làm tại Hà Nội']/parent::*</value>
      <webElementGuid>8c488071-86a1-4aff-96f2-a33cb8cf9ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b4b43f64-9e56-4b53-b9ef-93c503ee91ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
Việc làm tại Hà Nội
' or . = '
Việc làm tại Hà Nội
')]</value>
      <webElementGuid>73b66e53-5e5a-440f-ab5d-ae0827570393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
